# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

### Un poco más de teoría:
[Qué es un perceptrón?](https://datascientest.com/es/perceptron-que-es-y-para-que-sirve#:~:text=Un%20perceptr%C3%B3n%20es%20una%20neurona%20artificial%2C%20y%2C%20por%20tanto%2C,aprendizaje%20supervisado%20de%20clasificadores%20binarios.)

[Video Introducción al perceptrón simple](https://www.youtube.com/watch?v=bjMuj1d_yzQ)



In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [10]:
standardized_X_test[0:10,]

array([[ 0.48014902, -0.06555387,  0.58199692,  0.32502003],
       [ 0.61477024,  0.80849776,  1.08263943,  1.59683755],
       [ 0.3455278 , -1.81365714,  0.20651504, -0.2402322 ],
       [-1.00068441, -1.59514423, -0.23154716, -0.2402322 ],
       [ 1.0186339 , -0.50257969,  0.58199692,  0.46633309],
       [-0.86606319,  1.02701067, -1.42057313, -1.37073666],
       [-0.46219952,  1.9010623 , -1.48315344, -1.08811054],
       [-0.3275783 , -1.59514423,  0.20651504,  0.18370698],
       [-0.05833586, -0.28406678,  0.33167566,  0.18370698],
       [ 1.28787635,  0.15295904,  1.20780006,  1.73815061]])

In [11]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [12]:
y_pred = perceptron.predict(standardized_X_test)

In [13]:
print(y_test)

[1 2 1 1 1 0 0 1 1 2 0 0 0 2 1 1 0 0 2 2 1 2 0 1 2 1 2 1 1 0]


In [14]:
print(y_pred)

[2 2 1 1 2 0 0 1 1 2 0 0 0 2 1 1 0 0 2 2 2 2 0 2 2 1 2 1 1 0]


In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.69      0.82        13
           2       0.67      1.00      0.80         8

    accuracy                           0.87        30
   macro avg       0.89      0.90      0.87        30
weighted avg       0.91      0.87      0.87        30

